apiVersion: v1
kind: Pod

metadata:
  name: kibana
  labels:
    app: web-elasticsearch
    microservice: kivana
    version: v1

spec:
  containers:
    - name: kibana
      image: m4t30r0s4as/kibana:1.0
      env:
        - name: ELASTICSEARCH_URL
          valueFrom:
            configMapKeyRef:
              name: env-values
              key: ELASTICSEARCH_URL
      ports:
        - containerPort: 5601
      
      resources:
        limits:
          memory: 1Gi
          cpu: 1