apiVersion: v1
kind: Pod

metadata:
  name: mysql
  labels:
    app: web-elasticsearch
    microservice: mysql
    version: v1

spec:
  containers:
    - name: mysql
      image: m4t30r0s4as/mysql_elastic:1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-var-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
             name: env-values
             key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: env-values
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-var-secret
              key: MYSQL_PASSWORD
      ports:
        - containerPort: 3306