apiVersion: v1
kind: Service

metadata:
  name: svc-elasticsearch
  labels:
    app: web-elasticsearch
    version: v1

spec:
  type: ClusterIP
  selector:
    microservice: kibana
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
    - protocol: TCP
      port: 9300
      targetPort: 9300
