apiVersion: v1
kind: Service


metadata:
  name: svc-kibana
  labels:
    app: web-elasticsearch
    version: v1

spec:
  type: ClusterIP
  selector:
    microservice: elasticsearch
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601